In [75]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, balanced_accuracy_score, confusion_matrix, f1_score, precision_score, recall_score

In [84]:
def metrics(true, pred):
    print("Accuracy: ", accuracy_score(true, pred))
    print("Balanced Accuracy: ", balanced_accuracy_score(true, pred))
    print("F1 micro Score: ", f1_score(true, pred, average='micro'))
    print("F1 macro Score: ", f1_score(true, pred, average='macro'))
    print("Precision micro: ", precision_score(true, pred, average='micro'))
    print("Precision macro: ", precision_score(true, pred, average='macro'))
    print("Recall micro: ", recall_score(true, pred, average='micro'))
    print("Recall macro: ", recall_score(true, pred, average='macro'))
    print("Confusion Matrix")
    print(confusion_matrix(true, pred))

In [114]:
M3_test = pd.read_csv('./IDRID/Labels/Train/M3_predictions[0, 1].csv', index_col=0)
M2_train = pd.read_csv('./IDRID/Labels/Train/M2_predictions[0, 1].csv', index_col=0)
Ensemble_train = pd.read_csv('./IDRID/Labels/Train/Ensemble_predictions[0, 1].csv', index_col=0)
Labels_train = pd.read_csv('./IDRID/Labels/Train/labels.csv', index_col=0)
Labels_test = pd.read_csv('./IDRID/Labels/Test/labels.csv', index_col=0)
M1_0_train = pd.read_csv('./IDRID/Labels/Train/M1_predictions[0].csv', index_col=0)
M1_01_train = pd.read_csv('./IDRID/Labels/Train/M1_predictions[0, 1].csv', index_col=0)
M1_1_train = pd.read_csv('./IDRID/Labels/Train/M1_predictions[1].csv', index_col=0)

In [65]:
Labels_train['Retinopathy grade'].value_counts()

2    136
0    134
3     74
4     49
1     20
Name: Retinopathy grade, dtype: int64

In [87]:
Labels_train['Risk of macular edema'].value_counts()

2    195
0    177
1     41
Name: Risk of macular edema, dtype: int64

In [121]:
Labels_test['Risk of macular edema'].value_counts()

2    48
0    45
1    10
Name: Risk of macular edema, dtype: int64

In [97]:
metrics(Labels_train['Retinopathy grade'], M1_0_train.iloc[:,0:5].idxmax(axis=1).astype(np.int64))

Accuracy:  0.9346246973365617
Balanced Accuracy:  0.948530029196027
F1 micro Score:  0.9346246973365616
F1 macro Score:  0.9376847956224174
Precision micro:  0.9346246973365617
Precision macro:  0.9350043078964078
Recall micro:  0.9346246973365617
Recall macro:  0.948530029196027
Confusion Matrix
[[130   0   1   3   0]
 [  0  20   0   0   0]
 [  1   0 118  16   1]
 [  0   1   0  73   0]
 [  0   0   0   4  45]]


In [98]:
metrics(Labels_train['Retinopathy grade'], M1_01_train.iloc[:,0:5].idxmax(axis=1).astype(np.int64))

Accuracy:  0.6101694915254238
Balanced Accuracy:  0.7320949033102552
F1 micro Score:  0.6101694915254238
F1 macro Score:  0.5753576457517859
Precision micro:  0.6101694915254238
Precision macro:  0.5040513652977343
Recall micro:  0.6101694915254238
Recall macro:  0.7320949033102552
Confusion Matrix
[[132   2   0   0   0]
 [  0  20   0   0   0]
 [ 81  30   0  14  11]
 [ 18   2   0  53   1]
 [  1   1   0   0  47]]


C:\Users\mati2\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [100]:
metrics(Labels_train['Risk of macular edema'], (M1_01_train.iloc[:,5:10].idxmax(axis=1).astype(np.int64)-5))

Accuracy:  0.513317191283293
Balanced Accuracy:  0.5215759849906191
F1 micro Score:  0.513317191283293
F1 macro Score:  0.4756692009516046
Precision micro:  0.513317191283293
Precision macro:  0.8072923245337038
Recall micro:  0.513317191283293
Recall macro:  0.5215759849906191
Confusion Matrix
[[177   0   0]
 [ 21  20   0]
 [179   1  15]]


In [101]:
metrics(Labels_train['Risk of macular edema'], (M1_1_train.iloc[:,5:10].idxmax(axis=1).astype(np.int64)-5))

Accuracy:  0.9927360774818402
Balanced Accuracy:  0.9818565982269992
F1 micro Score:  0.9927360774818402
F1 macro Score:  0.9879972503392049
Precision micro:  0.9927360774818402
Precision macro:  0.9945540013758313
Recall micro:  0.9927360774818402
Recall macro:  0.9818565982269992
Confusion Matrix
[[176   0   1]
 [  2  39   0]
 [  0   0 195]]


In [115]:
Ensemble_train.iloc[:,0:5].idxmax(axis=1).value_counts()

0    135
2    117
3     93
4     47
1     21
dtype: int64

In [116]:
(Ensemble_train.iloc[:,5:10].idxmax(axis=1).astype(np.int64)-5).value_counts()

0    383
1     21
2      9
dtype: int64

In [117]:
metrics(Labels_train['Retinopathy grade'], Ensemble_train.iloc[:,0:5].idxmax(axis=1).astype(np.int64))

Accuracy:  0.937046004842615
Balanced Accuracy:  0.9526555600053654
F1 micro Score:  0.937046004842615
F1 macro Score:  0.9413206546545834
Precision micro:  0.937046004842615
Precision macro:  0.937056272485236
Recall micro:  0.937046004842615
Recall macro:  0.9526555600053654
Confusion Matrix
[[132   0   1   1   0]
 [  0  20   0   0   0]
 [  3   0 116  16   1]
 [  0   1   0  73   0]
 [  0   0   0   3  46]]


In [118]:
metrics(Labels_train['Risk of macular edema'], (Ensemble_train.iloc[:,5:10].idxmax(axis=1).astype(np.int64)-5))

Accuracy:  0.49878934624697335
Balanced Accuracy:  0.5113195747342089
F1 micro Score:  0.49878934624697335
F1 macro Score:  0.4551798138610282
Precision micro:  0.49878934624697335
Precision macro:  0.8048406481826847
Recall micro:  0.49878934624697335
Recall macro:  0.5113195747342089
Confusion Matrix
[[177   0   0]
 [ 21  20   0]
 [185   1   9]]


In [89]:
M2_train.iloc[:,0:5].idxmax(axis=1).value_counts()

0    410
2      3
dtype: int64

In [39]:
M2_train.iloc[:,5:10].idxmax(axis=1).value_counts()

5    413
dtype: int64

In [95]:
metrics(Labels_train['Retinopathy grade'], M2_train.iloc[:,0:5].idxmax(axis=1).astype(np.int64))

Accuracy:  0.33171912832929784
Balanced Accuracy:  0.20441176470588235
F1 micro Score:  0.33171912832929784
F1 macro Score:  0.10716250528988573
Precision micro:  0.33171912832929784
Precision macro:  0.2653658536585366
Recall micro:  0.33171912832929784
Recall macro:  0.20441176470588235
Confusion Matrix
[[134   0   0   0   0]
 [ 20   0   0   0   0]
 [133   0   3   0   0]
 [ 74   0   0   0   0]
 [ 49   0   0   0   0]]


C:\Users\mati2\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [94]:
metrics(Labels_train['Risk of macular edema'], (M2_train.iloc[:,5:10].idxmax(axis=1).astype(np.int64)-5))

Accuracy:  0.42857142857142855
Balanced Accuracy:  0.3333333333333333
F1 micro Score:  0.42857142857142855
F1 macro Score:  0.19999999999999998
Precision micro:  0.42857142857142855
Precision macro:  0.14285714285714285
Recall micro:  0.42857142857142855
Recall macro:  0.3333333333333333
Confusion Matrix
[[177   0   0]
 [ 41   0   0]
 [195   0   0]]


C:\Users\mati2\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [40]:
M3_test.iloc[:,0:5].idxmax(axis=1).value_counts()

0    103
dtype: int64

In [41]:
M3_test.iloc[:,5:10].idxmax(axis=1).value_counts()

5    103
dtype: int64

In [102]:
import torch
from torchvision import transforms
from itertools import combinations
import pandas as pd
from torch import nn
from torch.utils.data import DataLoader
from torch.nn.functional import softmax
from torch.optim.lr_scheduler import ReduceLROnPlateau
from Pipeline.Datasets import IDRiD_Dataset, IDRiD_Dataset_Teacher, IDRiD_Dataset_Unlabeled_Preds, IDRiD_Dataset2
from Pipeline.Models import MTL

In [111]:
def read_predictions(filename):
        table = pd.read_csv(filename, index_col=0)
        r_label, m_label = table.iloc[:, 0:5], table.iloc[:, 5:10]
        r_label = softmax(torch.tensor(r_label.values), dim=-1)
        m_label = softmax(torch.tensor(m_label.values), dim=-1)
        f_coords, o_coords = table.iloc[:, 10:12], table.iloc[:, 12:]
        return r_label, m_label, f_coords, o_coords

In [113]:
sub_data12 = read_predictions("./IDRID/Labels/train/M1_predictions[0, 1].csv")
sub_data1 = read_predictions("./IDRID/Labels/train/M1_predictions[0].csv")
sub_data2 = read_predictions("./IDRID/Labels/train/M1_predictions[1].csv")
joined_data = (sub_data1[0].numpy(),pd.DataFrame(sub_data1[1].numpy(), columns=[5, 6, 7, 8, 9]), sub_data2[2], sub_data2[3])
sub_data12 = (sub_data12[0].numpy(),pd.DataFrame(sub_data12[1].numpy(), columns=[5, 6, 7, 8, 9]), sub_data12[2],sub_data12[3])
voting = [pd.DataFrame(0.2 * x + 0.8 * y) for x, y in zip(sub_data12, joined_data)]
prediction = pd.concat(voting, axis=1)
prediction.to_csv('./IDRID/Labels/train/1Ensemble_predictions[0, 1].csv')

In [119]:
joined_data

(array([[4.05541309e-03, 3.28335102e-03, 4.27777691e-02, 9.49102835e-01,
         7.80631910e-04],
        [2.24160485e-04, 7.87970179e-04, 1.73442036e-02, 9.79406882e-01,
         2.23678388e-03],
        [6.33192856e-03, 1.68021640e-04, 8.65531700e-01, 1.15800236e-01,
         1.21681141e-02],
        ...,
        [9.59466544e-03, 5.64239865e-02, 7.24803484e-01, 2.08392550e-01,
         7.85314394e-04],
        [1.03976372e-01, 2.16380992e-02, 6.98898421e-01, 1.70333539e-01,
         5.15356811e-03],
        [4.72629646e-01, 5.79917212e-02, 4.36213365e-01, 2.33541172e-02,
         9.81114999e-03]]),
             5         6         7         8         9
 0    0.206127  0.205942  0.198028  0.195620  0.194284
 1    0.212193  0.201360  0.195899  0.191591  0.198957
 2    0.205312  0.197468  0.200694  0.194661  0.201865
 3    0.210356  0.196307  0.195179  0.198778  0.199380
 4    0.205578  0.197707  0.202610  0.195200  0.198905
 ..        ...       ...       ...       ...       ...
 408  

In [120]:
sub_data12

(array([[2.73525957e-01, 4.59170698e-02, 2.27686937e-04, 6.14494713e-01,
         6.58345730e-02],
        [5.78281960e-03, 3.48235541e-04, 3.32401171e-05, 9.93160134e-01,
         6.75571225e-04],
        [2.95293211e-01, 5.48627277e-01, 3.22522174e-02, 7.26112420e-02,
         5.12160520e-02],
        ...,
        [4.82534317e-01, 3.26516552e-01, 3.49305618e-02, 1.29833095e-01,
         2.61854743e-02],
        [9.84392489e-01, 3.64106085e-04, 8.95981696e-03, 3.57473676e-03,
         2.70885108e-03],
        [5.99058488e-01, 3.25785092e-01, 4.39269413e-03, 3.53447949e-02,
         3.54189305e-02]]),
             5         6         7         8         9
 0    0.935851  0.000043  0.064094  0.000006  0.000006
 1    0.537305  0.000118  0.462535  0.000019  0.000022
 2    0.868084  0.011716  0.119717  0.000244  0.000240
 3    0.946976  0.001080  0.051838  0.000054  0.000052
 4    0.940331  0.001312  0.058147  0.000107  0.000103
 ..        ...       ...       ...       ...       ...
 408  

In [125]:
W_T0 = torch.tensor([0.53, 2.13, 0.53, 0.74, 1.06])
W_T1 = torch.tensor([0.6,1.8,0.6])

In [126]:
W_T1 = torch.tensor([0.6,1.8,0.6])

tensor([ 0, 12,  1,  3,  4])

In [144]:
x = np.array([134,20,136,74,49])
(np.sum(x)-x)/np.mean(x)

array([3.37772397, 4.75786925, 3.3535109 , 4.10411622, 4.40677966])

In [141]:
(np.array([1,4,1,1.4,2])/9.4)*5

array([0.53191489, 2.12765957, 0.53191489, 0.74468085, 1.06382979])