In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, balanced_accuracy_score, confusion_matrix, f1_score, precision_score, recall_score

In [2]:
def metrics(true, pred):
    print("Accuracy: ", accuracy_score(true, pred))
    print("Balanced Accuracy: ", balanced_accuracy_score(true, pred))
    print("F1 micro Score: ", f1_score(true, pred, average='micro'))
    print("F1 macro Score: ", f1_score(true, pred, average='macro'))
    print("Precision micro: ", precision_score(true, pred, average='micro'))
    print("Precision macro: ", precision_score(true, pred, average='macro'))
    print("Recall micro: ", recall_score(true, pred, average='micro'))
    print("Recall macro: ", recall_score(true, pred, average='macro'))
    print("Confusion Matrix")
    print(confusion_matrix(true, pred))

In [3]:
M3_train = pd.read_csv('./IDRID/Labels/Train/M3_predictions[0, 1].csv', index_col=0)
M2_train = pd.read_csv('./IDRID/Labels/Train/M2_predictions[0, 1].csv', index_col=0)
Ensemble_train = pd.read_csv('./IDRID/Labels/Train/Ensemble_predictions[0, 1].csv', index_col=0)
Labels_train = pd.read_csv('./IDRID/Labels/Train/labels.csv', index_col=0)
Labels_test = pd.read_csv('./IDRID/Labels/Test/labels.csv', index_col=0)
M1_0_train = pd.read_csv('./IDRID/Labels/Train/M1_predictions[0].csv', index_col=0)
M1_01_train = pd.read_csv('./IDRID/Labels/Train/M1_predictions[0, 1].csv', index_col=0)
M1_1_train = pd.read_csv('./IDRID/Labels/Train/M1_predictions[1].csv', index_col=0)

In [4]:
Labels_train['Retinopathy grade'].value_counts()

2    136
0    134
3     74
4     49
1     20
Name: Retinopathy grade, dtype: int64

In [5]:
Labels_train['Risk of macular edema'].value_counts()

2    195
0    177
1     41
Name: Risk of macular edema, dtype: int64

In [6]:
Labels_test['Risk of macular edema'].value_counts()

2    48
0    45
1    10
Name: Risk of macular edema, dtype: int64

In [7]:
metrics(Labels_train['Retinopathy grade'], M1_0_train.iloc[:,0:5].idxmax(axis=1).astype(np.int64))

Accuracy:  0.8595641646489104
Balanced Accuracy:  0.9110095389507155
F1 micro Score:  0.8595641646489104
F1 macro Score:  0.8647267816516753
Precision micro:  0.8595641646489104
Precision macro:  0.8582668534367401
Recall micro:  0.8595641646489104
Recall macro:  0.9110095389507155
Confusion Matrix
[[134   0   0   0   0]
 [  0  20   0   0   0]
 [ 37   8  81   8   2]
 [  0   2   0  71   1]
 [  0   0   0   0  49]]


In [8]:
metrics(Labels_train['Retinopathy grade'], M1_01_train.iloc[:,0:5].idxmax(axis=1).astype(np.int64))

Accuracy:  0.7723970944309927
Balanced Accuracy:  0.8435561719645502
F1 micro Score:  0.7723970944309927
F1 macro Score:  0.7996372618471346
Precision micro:  0.7723970944309927
Precision macro:  0.8133350997644639
Recall micro:  0.7723970944309927
Recall macro:  0.8435561719645502
Confusion Matrix
[[97  1  6  3 27]
 [ 0 20  0  0  0]
 [11  0 92  1 32]
 [ 0  1  3 62  8]
 [ 1  0  0  0 48]]


In [9]:
metrics(Labels_train['Risk of macular edema'], (M1_01_train.iloc[:,5:8].idxmax(axis=1).astype(np.int64)-5))

Accuracy:  0.8305084745762712
Balanced Accuracy:  0.8742575691728233
F1 micro Score:  0.8305084745762712
F1 macro Score:  0.8320531982147159
Precision micro:  0.8305084745762712
Precision macro:  0.8058668804328765
Recall micro:  0.8305084745762712
Recall macro:  0.8742575691728233
Confusion Matrix
[[142   4  31]
 [  0  41   0]
 [ 23  12 160]]


In [10]:
metrics(Labels_train['Risk of macular edema'], (M1_1_train.iloc[:,5:8].idxmax(axis=1).astype(np.int64)-5))

Accuracy:  0.8547215496368039
Balanced Accuracy:  0.8899721930726479
F1 micro Score:  0.8547215496368039
F1 macro Score:  0.8887963092789302
Precision micro:  0.8547215496368039
Precision macro:  0.9064864864864864
Recall micro:  0.8547215496368039
Recall macro:  0.8899721930726479
Confusion Matrix
[[171   0   6]
 [  1  40   0]
 [ 53   0 142]]


In [11]:
Ensemble_train.iloc[:,0:5].idxmax(axis=1).value_counts()

0    152
2    105
3     78
4     54
1     24
dtype: int64

In [12]:
(Ensemble_train.iloc[:,5:8].idxmax(axis=1).astype(np.int64)-5).value_counts()

2    193
0    163
1     57
dtype: int64

In [13]:
metrics(Labels_train['Retinopathy grade'], Ensemble_train.iloc[:,0:5].idxmax(axis=1).astype(np.int64))

Accuracy:  0.9176755447941889
Balanced Accuracy:  0.9463036565977742
F1 micro Score:  0.9176755447941889
F1 macro Score:  0.9206379955510112
Precision micro:  0.9176755447941889
Precision macro:  0.9065152196731144
Recall micro:  0.9176755447941889
Recall macro:  0.9463036565977742
Confusion Matrix
[[134   0   0   0   0]
 [  0  20   0   0   0]
 [ 18   1 105   7   5]
 [  0   3   0  71   0]
 [  0   0   0   0  49]]


In [14]:
metrics(Labels_train['Risk of macular edema'], (Ensemble_train.iloc[:,5:8].idxmax(axis=1).astype(np.int64)-5))

Accuracy:  0.8256658595641646
Balanced Accuracy:  0.8704910908300739
F1 micro Score:  0.8256658595641646
F1 macro Score:  0.828335457894498
Precision micro:  0.8256658595641646
Precision macro:  0.802403165058986
Recall micro:  0.8256658595641646
Recall macro:  0.8704910908300739
Confusion Matrix
[[140   4  33]
 [  0  41   0]
 [ 23  12 160]]


In [15]:
M2_train.iloc[:,0:5].idxmax(axis=1).value_counts()

4    201
0     98
3     49
2     44
1     21
dtype: int64

In [16]:
M2_train.iloc[:,5:8].idxmax(axis=1).value_counts()

7    249
5    129
6     35
dtype: int64

In [17]:
metrics(Labels_train['Retinopathy grade'], M2_train.iloc[:,0:5].idxmax(axis=1).astype(np.int64))

Accuracy:  0.6077481840193705
Balanced Accuracy:  0.727575753980495
F1 micro Score:  0.6077481840193705
F1 macro Score:  0.6805437248855247
Precision micro:  0.6077481840193705
Precision macro:  0.8142787915709025
Recall micro:  0.6077481840193705
Recall macro:  0.727575753980495
Confusion Matrix
[[92  0  1  0 41]
 [ 0 20  0  0  0]
 [ 6  0 43  2 85]
 [ 0  1  0 47 26]
 [ 0  0  0  0 49]]


In [18]:
metrics(Labels_train['Risk of macular edema'], (M2_train.iloc[:,5:8].idxmax(axis=1).astype(np.int64)-5))

Accuracy:  0.8498789346246973
Balanced Accuracy:  0.8275391045957395
F1 micro Score:  0.8498789346246973
F1 macro Score:  0.8456784958332947
Precision micro:  0.8498789346246973
Precision macro:  0.8899553918887065
Recall micro:  0.8498789346246973
Recall macro:  0.8275391045957395
Confusion Matrix
[[127   2  48]
 [  0  32   9]
 [  2   1 192]]


In [19]:
M3_train.iloc[:,0:5].idxmax(axis=1).value_counts()

4    412
0      1
dtype: int64

In [20]:
M3_train.iloc[:,5:8].idxmax(axis=1).value_counts()

7    367
5     46
dtype: int64

In [32]:
metrics(Labels_train['Retinopathy grade'], M3_train.iloc[:,0:5].idxmax(axis=1).astype(np.int64))

Accuracy:  0.11864406779661017
Balanced Accuracy:  0.2
F1 micro Score:  0.11864406779661017
F1 macro Score:  0.04251626898047722
Precision micro:  0.11864406779661017
Precision macro:  0.023786407766990293
Recall micro:  0.11864406779661017
Recall macro:  0.2
Confusion Matrix
[[  0   0   0   0 134]
 [  0   0   0   0  20]
 [  1   0   0   0 135]
 [  0   0   0   0  74]
 [  0   0   0   0  49]]


C:\Users\mati2\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [30]:
metrics(Labels_train['Risk of macular edema'], (M3_train.iloc[:,5:8].idxmax(axis=1).astype(np.int64)-5))

Accuracy:  0.5375302663438256
Balanced Accuracy:  0.38539765319426333
F1 micro Score:  0.5375302663438256
F1 macro Score:  0.3246572937778274
Precision micro:  0.5375302663438256
Precision macro:  0.41713067172136004
Recall micro:  0.5375302663438256
Recall macro:  0.38539765319426333
Confusion Matrix
[[ 34   0 143]
 [  5   0  36]
 [  7   0 188]]


C:\Users\mati2\Anaconda\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [21]:
import torch
from torchvision import transforms
from itertools import combinations
import pandas as pd
from torch import nn
from torch.utils.data import DataLoader
from torch.nn.functional import softmax
from torch.optim.lr_scheduler import ReduceLROnPlateau
from Pipeline.Datasets import IDRiD_Dataset, IDRiD_Dataset_Teacher, IDRiD_Dataset_Unlabeled_Preds, IDRiD_Dataset2
from Pipeline.Models import MTL

In [35]:
def read_predictions(filename):
        table = pd.read_csv(filename, index_col=0)
        r_label, m_label = table.iloc[:, 0:5], table.iloc[:, 5:8]
        r_label = softmax(torch.tensor(r_label.values), dim=-1)
        m_label = softmax(torch.tensor(m_label.values), dim=-1)
        f_coords, o_coords = table.iloc[:, 8:10], table.iloc[:, 10:]
        return r_label, m_label, f_coords, o_coords

In [36]:
sub_data12 = read_predictions("./IDRID/Labels/train/M1_predictions[0, 1].csv")
sub_data1 = read_predictions("./IDRID/Labels/train/M1_predictions[0].csv")
sub_data2 = read_predictions("./IDRID/Labels/train/M1_predictions[1].csv")
joined_data = (sub_data1[0].numpy(),pd.DataFrame(sub_data1[1].numpy(), columns=[5, 6, 7]), sub_data2[2], sub_data2[3])
sub_data12 = (sub_data12[0].numpy(),pd.DataFrame(sub_data12[1].numpy(), columns=[5, 6, 7]), sub_data12[2],sub_data12[3])
voting = [pd.DataFrame(0.2 * x + 0.8 * y) for x, y in zip(sub_data12, joined_data)]
prediction = pd.concat(voting, axis=1)
prediction.to_csv('./IDRID/Labels/train/1Ensemble_predictions[0, 1].csv')

In [37]:
joined_data

(array([[1.37226527e-02, 8.10749700e-04, 2.50417604e-02, 9.54416917e-01,
         6.00792058e-03],
        [9.53399574e-04, 9.03124842e-04, 1.40959378e-02, 9.74389886e-01,
         9.65765171e-03],
        [3.37943449e-02, 5.19400023e-04, 7.50021268e-01, 1.83262924e-01,
         3.24020630e-02],
        ...,
        [9.36401414e-02, 1.68986669e-01, 6.33094331e-01, 1.00561069e-01,
         3.71778973e-03],
        [4.04886411e-01, 9.04670351e-02, 4.62559113e-01, 4.14004215e-02,
         6.87019475e-04],
        [5.32143969e-01, 7.20674299e-02, 3.69605704e-01, 1.84505240e-02,
         7.73237354e-03]]),
             5         6         7
 0    0.325315  0.330840  0.343845
 1    0.328305  0.322704  0.348991
 2    0.320232  0.322171  0.357596
 3    0.308590  0.332945  0.358465
 4    0.309564  0.327699  0.362738
 ..        ...       ...       ...
 408  0.317819  0.319099  0.363083
 409  0.322142  0.312340  0.365518
 410  0.324496  0.326584  0.348920
 411  0.325344  0.321691  0.352965
 412  

In [38]:
sub_data12

(array([[5.79746819e-02, 1.15883223e-02, 9.37517073e-02, 6.78125311e-01,
         1.58559977e-01],
        [2.49398401e-02, 6.80908952e-05, 2.86930728e-02, 9.45342247e-01,
         9.56748931e-04],
        [5.70891792e-03, 3.58551458e-03, 4.03923014e-01, 2.01758037e-02,
         5.66606750e-01],
        ...,
        [6.07881833e-02, 2.04797572e-02, 7.56569990e-01, 8.55246789e-02,
         7.66373907e-02],
        [1.29787504e-01, 6.16141717e-05, 7.35678296e-01, 1.05387646e-02,
         1.23933821e-01],
        [3.73663633e-01, 6.31233920e-02, 4.38410162e-01, 6.73799667e-02,
         5.74228469e-02]]),
             5         6         7
 0    0.151674  0.108880  0.739447
 1    0.046161  0.000643  0.953197
 2    0.022451  0.114514  0.863035
 3    0.201466  0.432983  0.365552
 4    0.273437  0.087845  0.638718
 ..        ...       ...       ...
 408  0.000967  0.979315  0.019719
 409  0.297467  0.102703  0.599830
 410  0.144704  0.666906  0.188390
 411  0.627761  0.042167  0.330072
 412  

In [39]:
W_T0 = torch.tensor([0.53, 2.13, 0.53, 0.74, 1.06])
W_T1 = torch.tensor([0.6,1.8,0.6])

In [40]:
W_T1 = torch.tensor([0.6,1.8,0.6])

In [41]:
x = np.array([134,20,136,74,49])
(np.sum(x)-x)/np.mean(x)

array([3.37772397, 4.75786925, 3.3535109 , 4.10411622, 4.40677966])

In [42]:
(np.array([1,4,1,1.4,2])/9.4)*5

array([0.53191489, 2.12765957, 0.53191489, 0.74468085, 1.06382979])